name: chat
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: "^1.4.0"
  firebase_auth: "^3.0.1"
  google_sign_in: ^5.0.7
  flutter_facebook_auth: "^3.5.0"
  provider: ^5.0.0
  cloud_firestore: "^2.5.0"
  shared_preferences: ^2.0.6
  image_picker: ^0.8.3+2
  flutter_spinkit: ^5.0.0
  awesome_dialog: ^2.1.1
  image_cropper: ^1.4.1
  path_provider: ^2.0.2
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/google_logo.png
    - assets/images/Facebook_logo.png
    - assets/images/star.png
    - assets/images/Logo.png
    - assets/images/Bg.png
    - assets/images/Brand.png
    - assets/images/LogoNoColor.png
    - assets/images/shield.png
    - assets/images/user.png
    - assets/images/blackUser.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
